allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
overrides:
  fflate@<0.7.5: 0.7.5
  nanoid@<3.3.18: 3.3.18
  postcss@<8.5.23: 8.5.29
  sharp@<0.35.5: 0.35.5
  source-map-js@<1.2.2: 1.2.2
