"use client";
import { useState, type Dispatch, type SetStateAction } from "react";
import CategorySettings from "./CategorySettings";
import GenericCsvImport from "./GenericCsvImport";
import { addOnboardingAccount, addOnboardingGoal, commitmentSuggestions, configureIncome, decideCommitment, incomeSuggestions, onboardingReview, ONBOARDING_STEPS, setOnboardingBalance } from "../lib/onboarding";
import type { AccountKind, CsvImportMapping, DirectDebitFrequency, OnboardingStep, Store } from "../lib/types";

const kinds:AccountKind[]=["current","savings","cash-isa","investment-isa","investment","credit-card","mortgage","loan","pension","property","other"];
const labels:Record<OnboardingStep,string>={welcome:"Welcome",accounts:"Accounts",import:"Import data",income:"Income & pay cycle",commitments:"Recurring commitments",categories:"Categories",goals:"Goals",review:"Review"};
type Props={store:Store;setStore:Dispatch<SetStateAction<Store>>;step:OnboardingStep;onStep:(step:OnboardingStep)=>void;onFinish:()=>void;onLeave:()=>void;onRestore:()=>void;onGeneric:(file:File,mapping:CsvImportMapping,save:boolean,applyBalance:boolean)=>Promise<void>;onMonzo:(file:File,accountId?:string)=>Promise<void>;onBarclaycard:(file:File,accountId?:string)=>Promise<void>;onCreateAccount:(name:string,kind:AccountKind)=>string;importError:string;notice:string};
const money=(amount:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(amount);

export default function Onboarding({store,setStore,step,onStep,onFinish,onLeave,onRestore,onGeneric,onMonzo,onBarclaycard,onCreateAccount,importError,notice}:Props){
  const [name,setName]=useState(""),[kind,setKind]=useState<AccountKind>("current"),[balance,setBalance]=useState(""),[asOf,setAsOf]=useState(new Date().toISOString().slice(0,10)),[coverage,setCoverage]=useState<"required"|"optional"|"excluded">("required");
  const [alias,setAlias]=useState(""),[incomeKind,setIncomeKind]=useState<"salary"|"rental">("salary"),[payday,setPayday]=useState(String(store.profile?.paySchedule?.payday??"")),[goalType,setGoalType]=useState<"emergency"|"custom">("emergency"),[goalName,setGoalName]=useState(""),[goalTarget,setGoalTarget]=useState(""),[error,setError]=useState("");
  const [commitmentEdits,setCommitmentEdits]=useState<Record<string,{amount:string;frequency:DirectDebitFrequency}>>({});
  const [cardAccountId,setCardAccountId]=useState("");
  const index=ONBOARDING_STEPS.indexOf(step),review=onboardingReview(store),suggestions=incomeSuggestions(store.transactions),commitments=commitmentSuggestions(store);
  const cardAccounts=store.profile?.accounts.filter(account=>account.kind==="credit-card")??[];
  const selectedCardAccount=cardAccounts.some(account=>account.id===cardAccountId)?cardAccountId:cardAccounts[0]?.id;
  const save=(change:()=>void)=>{try{change();setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Please check these details.")}};
  const next=()=>onStep(ONBOARDING_STEPS[Math.min(index+1,ONBOARDING_STEPS.length-1)]);
  const previous=()=>onStep(ONBOARDING_STEPS[Math.max(0,index-1)]);
  const addAccount=()=>save(()=>{const parsed=balance.trim()===""?undefined:Number(balance);if(!name.trim())throw new Error("Enter an account name.");if(parsed!==undefined&&(!Number.isFinite(parsed)||parsed<0))throw new Error("Enter a valid non-negative balance.");if(parsed!==undefined&&!asOf)throw new Error("Choose the balance date.");setStore(current=>addOnboardingAccount(current,{id:`account-${crypto.randomUUID()}`,name,kind,balance:parsed,asOf,coverage}));setName("");setBalance("")});
  const saveIncome=(source:string)=>save(()=>{const day=payday.trim()?Number(payday):undefined;if(!source.trim())throw new Error("Enter an income payee.");if(day!==undefined&&(!Number.isInteger(day)||day<1||day>31))throw new Error("Payday must be from 1 to 31.");setStore(current=>configureIncome(current,source,incomeKind,day));setAlias("")});
  const confirmSuggestion=(source:string,kind:"salary"|"rental")=>save(()=>{const day=kind==="salary"&&payday.trim()?Number(payday):undefined;if(day!==undefined&&(!Number.isInteger(day)||day<1||day>31))throw new Error("Payday must be from 1 to 31.");setStore(current=>configureIncome(current,source,kind,day))});
  const savePayday=()=>save(()=>{const day=Number(payday);if(!Number.isInteger(day)||day<1||day>31)throw new Error("Payday must be from 1 to 31.");setStore(current=>({...current,profile:current.profile?{...current.profile,paySchedule:{payday:day,rules:current.profile.paySchedule?.rules??[]}}:current.profile,payday:day,paydayRules:current.profile?.paySchedule?.rules??[]}))});
  const addGoal=()=>save(()=>{const target=Number(goalTarget),name=goalType==="emergency"?"Emergency fund":goalName;if(!name.trim()||!Number.isFinite(target)||target<=0)throw new Error("Enter a goal name and positive target.");if(goalType==="emergency"&&store.goals.some(goal=>goal.id==="ef"))throw new Error("Your emergency-fund goal already exists.");setStore(current=>addOnboardingGoal(current,{id:goalType==="emergency"?"ef":`goal-${crypto.randomUUID()}`,name,target}));setGoalName("");setGoalTarget("")});
  return <section className="onboarding" aria-labelledby="onboarding-title">
    <header className="onboarding-head"><div><span className="insight-label">LOCAL SETUP · STEP {index+1} OF {ONBOARDING_STEPS.length}</span><h1 id="onboarding-title">{labels[step]}</h1><p>Your progress and settings are saved on this device as you go.</p></div><button className="ghost" onClick={onLeave}>Leave setup</button></header>
    <ol className="onboarding-progress" aria-label="Setup progress">{ONBOARDING_STEPS.map((item,i)=><li key={item} aria-current={item===step?"step":undefined}><button onClick={()=>onStep(item)} aria-label={`Go to ${labels[item]}`}>{i+1}. {labels[item]}</button></li>)}</ol>
    {error&&<p className="import-error" role="alert">{error}</p>}{importError&&<p className="import-error" role="alert">{importError}</p>}{notice&&<p role="status">{notice}</p>}
    {step==="welcome"&&<article className="panel"><h2>Welcome to Personal CFO</h2><p>Your finances stay in this browser on this device. Add your accounts and, if you wish, import your own statements. You can leave and resume at any time.</p><div className="onboarding-actions"><button className="primary" onClick={next}>Get started</button><button className="ghost" onClick={onRestore}>Restore from a backup</button></div></article>}
    {step==="accounts"&&<><article className="panel"><h2>Your accounts</h2><p>Add as many accounts of each kind as you need. A provider name is optional; a dated balance makes cash and net-worth views useful.</p><div className="onboarding-fields"><label>Account name<input value={name} onChange={event=>setName(event.target.value)} placeholder="Main current account"/></label><label>Kind<select value={kind} onChange={event=>{const nextKind=event.target.value as AccountKind;setKind(nextKind);setCoverage(nextKind==="current"||nextKind==="credit-card"?"required":"excluded")}}>{kinds.map(item=><option key={item} value={item}>{item.replaceAll("-"," ")}</option>)}</select></label><label>Balance (optional)<input type="number" min="0" step="0.01" value={balance} onChange={event=>setBalance(event.target.value)}/></label><label>Balance as of<input type="date" value={asOf} onChange={event=>setAsOf(event.target.value)}/></label><label>Statement coverage<select value={coverage} onChange={event=>setCoverage(event.target.value as typeof coverage)}><option value="required">Required for complete reviews</option><option value="optional">Optional</option><option value="excluded">Exclude from transaction coverage</option></select></label></div><button className="primary" onClick={addAccount}>Add account</button></article><article className="panel"><h3>Accounts added</h3>{store.profile?.accounts.length?<div className="onboarding-list">{store.profile.accounts.map(account=>{const saved=store.balances.find(item=>item.id===account.id);return <div key={account.id}><strong>{account.name}</strong><span>{account.kind} · {account.coverage}</span><label>Current balance<input type="number" min="0" step="0.01" aria-label={`Balance for ${account.name}`} value={saved?.asOf?saved.value:""} onChange={event=>{const value=Number(event.target.value);if(event.target.value===""||!Number.isFinite(value)||value<0)return;setStore(current=>setOnboardingBalance(current,account.id,value,asOf))}}/></label><small>{saved?.asOf?`As of ${saved.asOf}`:"No dated balance yet"}</small></div>})}</div>:<p>No accounts added yet. You can continue and return later.</p>}</article></>}
    {step==="import"&&<><p>Import a bank CSV or card statement. Known providers are shortcuts; the generic mapper works with other CSV exports. Every import has a preview, duplicate check, and undo path.</p><GenericCsvImport accounts={store.profile?.accounts??[]} mappings={store.profile?.csvMappings??[]} onGeneric={onGeneric} onMonzo={onMonzo} onBarclaycard={onBarclaycard} onCreateAccount={onCreateAccount}/><article className="panel"><h3>Barclaycard PDF or CSV</h3><p>If you use Barclaycard, select its PDF or CSV here. Otherwise use the generic CSV mapper above.</p><label>Card account<select aria-label="Card account for Barclaycard PDF" value={selectedCardAccount??""} onChange={event=>setCardAccountId(event.target.value)}><option value="">Choose account</option>{cardAccounts.map(account=><option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Barclaycard statement<input type="file" accept=".pdf,.csv,application/pdf,text/csv" disabled={!selectedCardAccount} onChange={event=>{const file=event.target.files?.[0];if(file&&selectedCardAccount)void onBarclaycard(file,selectedCardAccount);event.target.value=""}}/></label>{!cardAccounts.length&&<p>Add a credit-card account first.</p>}</article><p>{store.imports?.length??0} files imported · {store.transactions.length} transactions available. You can skip this step.</p></>}
    {step==="income"&&<article className="panel"><h2>Income and payday</h2><p>Recurring credits are suggestions only. Confirm a payee to treat it as salary or rental income; nothing is labelled automatically.</p>{suggestions.length?<div className="onboarding-list">{suggestions.map(item=><div key={item.key}><strong>{item.merchant}</strong><span>{money(item.amount)} · {item.count} credits</span><button className="ghost" onClick={()=>confirmSuggestion(item.merchant,"salary")}>Confirm salary</button><button className="ghost" onClick={()=>confirmSuggestion(item.merchant,"rental")}>Confirm rental income</button></div>)}</div>:<p>No repeated credits found. You can add an income source manually.</p>}<div className="onboarding-fields"><label>Income payee / alias<input value={alias} onChange={event=>setAlias(event.target.value)} placeholder="Employer or payer name"/></label><label>Income type<select value={incomeKind} onChange={event=>setIncomeKind(event.target.value as typeof incomeKind)}><option value="salary">Salary</option><option value="rental">Rental income</option></select></label><label>Nominal payday (1–31)<input type="number" min="1" max="31" value={payday} onChange={event=>setPayday(event.target.value)}/></label></div><p>For a fixed payday, weekends move to the previous working day. You can adjust the schedule later in Settings.</p><div className="onboarding-actions"><button className="ghost" onClick={()=>saveIncome(alias)}>Save income source</button><button className="ghost" onClick={savePayday}>Save payday only</button></div><p>Configured: {store.profile?.incomeSources?.map(source=>`${source.kind}: ${source.merchantContains.join(", ")}`).join(" · ")||"No income source"} · payday {store.profile?.paySchedule?.payday??"not set"}</p></article>}
    {step==="commitments"&&<article className="panel"><h2>Regular commitments</h2><p>Review likely repeated payments. Card payments, transfers, and direct debits can all be commitments. Ordinary repeated shopping needs stronger evidence before it appears here.</p>{commitments.length?<div className="onboarding-list">{commitments.map(item=>{const edit=commitmentEdits[item.id]??{amount:String(item.scheduledAmount),frequency:item.frequency};return <div key={item.id}><strong>{item.label}</strong><span>{item.paymentMethod} · {item.category} · {item.source}</span><small>{item.count} matching payments · {item.archived?"Rejected":item.status==="detected"?"Needs confirmation":"Confirmed"}</small><label>Expected amount<input type="number" min="0.01" step="0.01" aria-label={`Expected amount for ${item.label}`} value={edit.amount} onChange={event=>setCommitmentEdits(current=>({...current,[item.id]:{...edit,amount:event.target.value}}))}/></label><label>Frequency<select aria-label={`Frequency for ${item.label}`} value={edit.frequency} onChange={event=>setCommitmentEdits(current=>({...current,[item.id]:{...edit,frequency:event.target.value as DirectDebitFrequency}}))}>{["weekly","monthly","quarterly","annual","irregular"].map(value=><option key={value} value={value}>{value}</option>)}</select></label><button className="ghost" onClick={()=>save(()=>{const amount=Number(edit.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error("Enter a positive commitment amount.");setStore(current=>decideCommitment(current,{...item,frequency:edit.frequency},"confirm",amount))})}>Confirm</button><button className="ghost" onClick={()=>setStore(current=>decideCommitment(current,item,"reject"))}>Not recurring</button></div>})}</div>:<p>No likely commitments yet. Import history or add them later; you can skip for now.</p>}</article>}
    {step==="categories"&&<><p>Keep the starter categories or tailor them. Plan groups tell the app whether spending is essential, lifestyle, saving, income, transfer, property, or work-related.</p><CategorySettings store={store} setStore={setStore}/></>}
    {step==="goals"&&<article className="panel"><h2>Optional goals</h2><p>Set an emergency fund, savings goal, or another target. No target is prefilled for you. The emergency fund follows your cash accounts.</p><div className="onboarding-fields"><label>Goal type<select value={goalType} onChange={event=>setGoalType(event.target.value as typeof goalType)}><option value="emergency">Emergency fund</option><option value="custom">Custom savings goal</option></select></label>{goalType==="custom"&&<label>Goal name<input value={goalName} onChange={event=>setGoalName(event.target.value)} placeholder="Your goal"/></label>}<label>Target<input type="number" min="0.01" step="0.01" value={goalTarget} onChange={event=>setGoalTarget(event.target.value)}/></label></div><button className="ghost" onClick={addGoal}>Add goal</button><div className="onboarding-list">{store.goals.map(goal=><div key={goal.id}><strong>{goal.name}</strong><span>{money(goal.target)} target</span></div>)}</div></article>}
    {step==="review"&&<article className="panel"><h2>Ready when you are</h2><div className="onboarding-summary"><span>Accounts <strong>{review.accounts}</strong></span><span>Transactions <strong>{review.transactions}</strong></span><span>Imported files <strong>{review.imports}</strong></span><span>Income sources <strong>{review.incomeSources}</strong></span><span>Payday <strong>{review.payday??"Not set"}</strong></span><span>Confirmed commitments <strong>{review.commitments}</strong></span><span>Categories <strong>{review.categories}</strong></span><span>Goals <strong>{review.goals}</strong></span></div>{review.warnings.length>0&&<div role="status"><h3>What will remain limited</h3><ul>{review.warnings.map(item=><li key={item}>{item}</li>)}</ul></div>}<p>You can finish with a partial setup and update anything later. These are the same accounts and profile the dashboard uses.</p><button className="primary" onClick={onFinish}>Finish setup</button></article>}
    {step!=="welcome"&&<footer className="onboarding-actions"><button className="ghost" onClick={previous}>Back</button>{step!=="review"&&<button className="primary" onClick={next}>{["import","commitments","goals"].includes(step)?"Continue or skip":"Continue"}</button>}</footer>}
  </section>;
}
